# Hey Emacs, this is -*- coding: utf-8; mode: bazel -*-

cc_library(
  name = "signal_processors",
  hdrs = [
    "SignalProcessors.hpp",
    "DataStreams.hpp",
  ],
  include_prefix = "signal_processors/",
  visibility = ["//visibility:public"],
)
