#!/bin/bash

set -eu
set -o pipefail

SPATH="$(dirname "${BASH_SOURCE[0]}")"
if [ ! -d "$SPATH" ]; then SPATH="$PWD"; fi
SPATH="$(cd -P "$SPATH" && pwd)"

PRJ_ROOT_PATH="$SPATH/.."
PRJ_ROOT_PATH="$(cd "$PRJ_ROOT_PATH" && pwd)"
META_PATH="$(cd "$PRJ_ROOT_PATH/.meta" && pwd)"

cd "$PRJ_ROOT_PATH" && echo cd $PWD

export CC=gcc-8

# bazel build //debug --verbose_failures
bazel build -s //debug
bazel build -s //reflection
bazel build -s //inline

bazel build -s //:compdb
chmod a-x,ug+w bazel-bin/compile_commands.json

"$META_PATH/bazel-compdb/unbox" \
  bazel-bin/compile_commands.json "$PRJ_ROOT_PATH"
