#!/bin/bash

PRJ_PATH="`dirname \"${BASH_SOURCE[0]}\"`"
if [[ ! -d "$PRJ_PATH" ]]; then PRJ_PATH="$PWD"; fi
PRJ_PATH="`( cd \"$PRJ_PATH\" && pwd )`"
source "$PRJ_PATH/paths"

cd $PRJ_ROOT_PATH && echo cd $PRJ_ROOT_PATH

# bazel build //server:cwt-storybook --verbose_failures
bazel build -s //debug
bazel build -s //reflection

bazel build -s //:compdb --define exec_root=$(bazel info execution_root)

chmod a-x,ug+w bazel-genfiles/compile_commands.json

$PRJ_PATH/compdb/merge -o bazel-genfiles/compile_commands.json \
                       bazel-genfiles/compile_commands.json
