#!/bin/bash

PRJ_PATH="`dirname \"${BASH_SOURCE[0]}\"`"
if [[ ! -d "$PRJ_PATH" ]]; then PRJ_PATH="$PWD"; fi
PRJ_PATH="`( cd \"$PRJ_PATH\" && pwd )`"
source "$PRJ_PATH/paths"

cd $PRJ_ROOT_PATH
# bazel build //server:cwt-storybook --verbose_failures
bazel clean
