#!/bin/bash

set -eu
set -o pipefail

SPATH="$(dirname "${BASH_SOURCE[0]}")"
if [ ! -d "$SPATH" ]; then SPATH="$PWD"; fi
SPATH="$(cd -P "$SPATH" && pwd)"

PRJ_ROOT_PATH="$SPATH/.."
PRJ_ROOT_PATH="$(cd "$PRJ_ROOT_PATH" && pwd)"

cd "$PRJ_ROOT_PATH" && echo cd $PWD

.project/build

if [[ ! -d .project/genfiles ]]; then
  mkdir .project/genfiles
fi

if [[ -f .project/genfiles/compile_commands.json ]]; then
  rm -vf .project/genfiles/compile_commands.json
fi

.project/compdb/merge -o .project/genfiles/compile_commands.json \
                          bazel-genfiles/compile_commands.json

cd .project/genfiles
rc -J -V .
#rc -J .
