cc_library(
  name = "reflection",
  hdrs = [
    "RH_ENUM_SHELL.hpp",
    "RH_FOR_EACH_P1.h",
    "RH_STRINGIFY.h",
    "refactorables.hpp",
  ],
  include_prefix = "reflection/",
  visibility = ["//visibility:public"],
)
